spring:
  application:
    name: drug_addict_management
  datasource:
    url: jdbc:mysql://localhost:3306/drug_addict_management
    username: thanh
    password: Abc@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

config:
  mail:
    system_email: q.cbeo223@gmail.com
    password: hiacsbrodknvshik
    host: smtp.gmail.com
    port: 587
  jwt_key: jwt_key_system
  expire_time:
    access_token: 6000000
    refresh_token: 12000000